# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0003_vod'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='posts',
            field=models.ManyToManyField(to='Annotation.Post'),
        ),
    ]
