# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0004_vod_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vod',
            name='posts',
        ),
        migrations.AddField(
            model_name='vod',
            name='posts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Annotation.Post'),
        ),
    ]
