# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0005_auto_20160911_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vod',
            name='posts',
        ),
        migrations.AddField(
            model_name='vod',
            name='posts',
            field=models.ManyToManyField(to='Annotation.Post'),
        ),
    ]
