# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0008_auto_20160925_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vod',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
