# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0009_auto_20160925_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
