# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0010_auto_20160929_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='tags',
            field=models.TextField(default='', max_length=60),
        ),
    ]
