# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0011_vod_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vod',
            name='tags',
            field=models.TextField(default='', max_length=100),
        ),
    ]
