# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Annotation', '0012_auto_20161003_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votedOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Annotation.Post')),
            ],
        ),
    ]
