# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0014_auto_20161004_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Annotation.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='poster',
            name='votedOn',
            field=models.ManyToManyField(to='Annotation.Votes'),
        ),
    ]
