# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0015_auto_20161004_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='votedOn',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='post',
        ),
        migrations.DeleteModel(
            name='Poster',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
