# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0016_auto_20161004_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='up',
        ),
        migrations.AddField(
            model_name='post',
            name='voteCount',
            field=models.IntegerField(default=0),
        ),
    ]
