# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0017_auto_20161004_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='voteCount',
            new_name='vote_count',
        ),
    ]
