# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0018_auto_20161007_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vod',
            name='tags',
        ),
    ]
